# Generated by Django 3.1 on 2022-04-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220426_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
